### ISSUE TITLE
Prototipado de baja fidelidad

### ISSUE THREAD

**Issue by MarytereBenavides** [MarytereBenavides/LIM014-social-network#1]
- [x] Prototipado de baja fidelidad
- [x] Testeo del prototipado de baja fidelidad

**Comment by MarytereBenavides** [comment]
- Cambiar el color del botón principal para lograr un contraste
- Tener un fondo degradado

**Comment by dmarinel** [comment]
Para definir la paleta de colores, se realizó el testeo con 10 personas
